### PR TITLE
16 pushapi standard

### PR DESCRIPTION
**Pull request by bengansukh**
I couldn't find PushMessageData endpoints in both Firefox and Chrome,

### CODE REVIEW

**Comment by elliott-beach** [comment]
I think `PushMessageData` objects are returned by the API to subscribed clients, so it's not something that needs to be blacklisted. See https://developer.mozilla.org/enUS/docs/Web/API/PushMessageData#Examples.

**Comment by elliott-beach** [comment]
I think `PushMessageData` objects are returned by the API to subscribed clients, so it's not something that needs to be blacklisted. See https://developer.mozilla.org/enUS/docs/Web/API/PushMessageData#Examples.

**Comment by elliott-beach** [comment]
I think `PushMessageData` objects are returned by the API to subscribed clients, so it's not something that needs to be blacklisted. See https://developer.mozilla.org/enUS/docs/Web/API/PushMessageData#Examples.

**Comment by elliott-beach** [comment]
I think `PushMessageData` objects are returned by the API to subscribed clients, so it's not something that needs to be blacklisted. See https://developer.mozilla.org/enUS/docs/Web/API/PushMessageData#Examples.

**Comment by elliott-beach** [comment]
I think `PushMessageData` objects are returned by the API to subscribed clients, so it's not something that needs to be blacklisted. See https://developer.mozilla.org/enUS/docs/Web/API/PushMessageData#Examples.

**Comment by elliott-beach** [comment]
I also discovered that gmail and google docs, and presumably the rest of Google's suite fail to load when this extension is enabled.

**Comment by snyderp** [comment]
@elliott-beach Thanks for updating the Wiki!  If you all are interested in tackling another standard, please let me know.  Would be very happy to work with you and your team!

**Comment by snyderp** [comment]
@bengansukh thanks for the PRs. I'll merge these in, but two requests for going forward:

1. Please make sure you have one PR per issue (I know we discussed, but just wanted to emphasize)
2. Please make sure your text files end with a new line

Thanks a ton for these!

**Pull request merged**
